- name: Include common directories
  ansible.builtin.import_tasks: dirs.yml

- name: Include SSH hygiene tasks
  ansible.builtin.import_tasks: ssh.yml

- name: Include common packages
  ansible.builtin.import_tasks: packages.yml
